name : Build and Deploy

on:
  push:
    branches: [ main ]


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install requirements.txt

      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - name: echo hello selenuim
        run: echo 'hello selenuim'